baseURL: 'http://theredone.io/'
languageCode: en-us
author: TheRedOne
title: ThereDone
theme:
  - casper3
mainSections:
  - posts

enableRobotsTXT: true

enableInlineShortcodes: true

enableEmoji: true

params:
  description: Building the homelab and other interesting things.
  mainSections:
    - post

copyright: >-
  Copyright © 2020

taxonomies:
  category: categories
  tag: tags
  series: series