---
baseURL: 'http://theredone.io/'
defaultContentLanguage: en
languageCode: en
title: ThereDone
theme: LoveIt
params:
  version: 0.2.X
  page:
    code: 
      copy: true
menu:
  main:
    - identifier: posts
      pre: ''
      post: ''
      name: Posts
      url: /posts/
      title: ''
      weight: 1
    - identifier: tags
      pre: ''
      post: ''
      name: Tags
      url: /tags/
      title: ''
      weight: 2
    - identifier: categories
      pre: ''
      post: ''
      name: Categories
      url: /categories/
      title: ''
      weight: 3
markup:
  highlight:
    noClasses: false
enableEmoji: true